# Generated by Django 2.0.4 on 2018-05-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabinfo',
            name='unit_mg',
            field=models.IntegerField(),
        ),
    ]
